name: Testing Workflow
on:
  push:
    branches:
      - develop
      - feature/*
  pull_request:
    branches:
      - develop
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'push' && startsWith(github.ref, 'refs/heads/feature/')) ||
      (github.event_name == 'pull_request')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Integration and Unit tests
        run: mvn test -B
        
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    outputs:
      version: ${{ steps.extract-version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Extract version from pom.xml
        id: extract-version
        run: |
          echo "Extracting version from pom.xml..."
          NEW_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "NEW_VERSION=$NEW_VERSION"
          echo "version=$NEW_VERSION" >> "$GITHUB_OUTPUT"

      - name: Build & Push Docker Image
        run: |
          mvn spring-boot:build-image -DskipTests -DdockerPassword=${{ secrets.DOCKER_PASSWORD }}

  update-manifests:
    name: Update Kubernetes Manifest
    runs-on: ubuntu-latest
    needs: build-and-push
    if: needs.build-and-push.outputs.version != ''
    steps:
      - name: Checkout Kubernetes manifests repository
        uses: actions/checkout@v4
        with:
          repository: CampusMov/k8s
          ref: develop
          token: ${{ secrets.K8S_GITHUB_TOKEN }}
          path: k8s

      - name: Update Kubernetes manifests
        working-directory: k8s/manifests/applications
        run: |
          NEW_VERSION="${{ needs.build-and-push.outputs.version }}"
          sed -i "s|\(image: jhosepmyr/uni-ride_profile-service:\).*|\1${NEW_VERSION}|" profile-service.yaml
          git diff profile-service.yaml

      - name: Commit and push changes
        working-directory: k8s/manifests/applications
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Actions Bot"
          git add profile-service.yaml
          if ! git diff --cached --quiet; then
            NEW_VERSION=$(echo "${{ needs.build-and-push.outputs.version }}" | tr -d '\n')
            git commit -m "Update profile-service image to ${NEW_VERSION}"
            git push origin main
          else
            echo "No changes detected. Skipping commit."
          fi